### PR TITLE
removed output files from repo

### PR DESCRIPTION
**Pull request by smolins**

### CODE REVIEW

**Comment by ecoon** [comment]
Sorry for the delay, I'm now back at work at Oak Ridge, and will be more responsive.  If you're going to actively be making changes here frequently (to demos you add/write), let me know and I'll make sure you have direct push privileges.

**Comment by smolins** [comment]
Hey Ethan

Could you please give add/write permissions to the ats-demos github repo?
Thanks

Sergi

**Comment by ecoon** [comment]
I think I just invited you to the ATS developers team, which should open up write privileges.  Let me know if you don't see it.

**Comment by smolins** [comment]
No invite so far and tried unsuccessfully to push a commit.

**Comment by jd-moulton** [comment]
Hi Sergi,

I add you, it failed quietly the first time for no obvious reason.  It seems to have worked this time.

Please give it a try again.

Thanks, David

**Comment by smolins** [comment]
Thank you. This worked.

**Comment by ecoon** [comment]
Thanks David, I looked for the "pending invite" thing but didn't see it, wasn't sure if it wasn't there or if I wasn't looking in the right spot.

**Pull request merged**
