### PR TITLE
Add Dockerfile, update instructions, and feedback

### PR DESCRIPTION
**Pull request by banesullivan**
I had some trouble getting these demos up and running, so here is a Dockerfile that I created which will hopefully mitigate these issues for other users.

### Some Notes

- This uses Python 2 which has reached end of life. The Python source code upstream in Amanzi and ATS need to be updated to Python 3
- @jd-moulton, it might be best to set the `ATS_SRC_DIR` environment variable upstream in the `metsi/ats` image
- Example 6 has 1 skipped test
- Example 5 has 1 **failing** test
- **All tests fail** for example 8
- I get the following warning on every run, should this be addressed?:

    ```
    ** WARNING ** : mpiexec was not provided on the command line.
                    All parallel tests will be skipped!
    ```
- I set up Python from the miniconda docker image. Are there any other Python packages that should be installed?
- Ideally, we should set up these examples so that they can be run from within the notebooks and set up the Docker container so that it launches Jupyter notebook or lab and the user simply opens the notebook for the given example

### CODE REVIEW

**Comment by banesullivan** [comment]
> Ideally, we should set up these examples so that they can be run from within the notebooks and set up the Docker container so that it launches Jupyter notebook or lab and the user simply opens the notebook for the given example

Having this would likely require the development of a Python helper package in Amanzi that would enable users to set input files and Amanzi/ATS run flags via a class. E.g.:

```py
class AmanziRun():
    def __init__(self, input_file, **args, **kwargs):
        # Set input file
        # set flags via the kwargs
        ...

    def run(self):
        # make call to Amanzi with defined flags and input file
        ...

# Same for ATS
class ATSRun(AmanziRun):
    ...
```

**Comment by ecoon** [comment]
The warning is easily removed by adding "-e `which mpiexec`" to the options provided on
 the command line.

> > Ideally, we should set up these examples so that they can be run from within the notebooks and set up the Docker container so that it launches Jupyter notebook or lab and the user simply opens the notebook for the given example
> 
> Having this would likely require the development of a Python helper package in Amanzi that would enable users to set input files and Amanzi/ATS run flags via a class. E.g.:

Haha, you're finding all of the ugly warts that need updating/revisiting.  We have a particularly hacky version of this that has been used by a few people.  The typical use of this is to run, for instance, parameter sensitivity studies, where they want to read a "template" input file, replace a few parameter values, and then spawn a run:

https://github.com/amanzi/ats/blob/master/tools/utils/atsxml/atsxml.py

The "example" in that directory isn't even a very good one (it doesn't spawn a run).  I'll push a new one in a minute.  Typically atsxml gets called from MATK: https://github.com/dharp/matk).  The single function in that file would accept a set of parameters, write an xml file, and spawn the run in a subdirectory.  It isn't exactly what you're looking for, but is similar.

**Comment by ecoon** [comment]
@banesullivan @jd-moulton  My guess is that the 08 demos fail because Amanzi's TPLs were not configured with geochemistry?  They look for a Reactive Transport PK.

What is the ATS/Amanzi/TPLs build versions/bootstrap options in metsi/ats?

**Comment by banesullivan** [comment]
> My guess is that the 08 demos fail because Amanzi's TPLs were not configured with geochemistry? They look for a Reactive Transport PK.


Looks like example 8 is failing due to:

```
terminate called after throwing an instance of 'Errors::Message'
  what():  PK Factory: PK "Flow and Reactive Transport" requested type "flow reactive transport ATS" which is not a registered PK type.
```

**Comment by ecoon** [comment]
Yes, the "flow reactive transport ATS" pk gets compiled only if there are TPLs that support the reactions.  That requires Amanzi and its TPLs to be built with Alquimia enabled, and likely PFLOTRAN too.  This sounds like the docker image for TPLs needs to be updated to add a broader suite of TPLs?

I'm happy to merge this now if you want or wait until the docker image is updated.  But if you'd like to merge it now, please add some documentation explaining that it doesn't work for reactive transport (just because otherwise someone will use it and then think the example is broken).

**Comment by banesullivan** [comment]
> I'm happy to merge this now if you want or wait until the docker image is updated. But if you'd like to merge it now, please add some documentation explaining that it doesn't work for reactive transport (just because otherwise someone will use it and then think the example is broken).

Let's hold off on merging this... there's no rush at the moment and it'd be better to merge when we have a solid Docker image that will work without caveats.

I may also make a few additional Docker images for our upcoming demo that would be good to include here as well. I am thinking it would be nice to have an image that can accept an archive of files (mesh, met data, and an ATS input file) then run the simulation without user interaction, and return the results as an archive of files (LOG, visdump files, observations, etc).

**Pull request closed without merging**
